
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2
{

using System;
    using System.Collections.Generic;
    
public partial class LocData
{

    public int Loc_ID { get; set; }

    public string Loc_Area { get; set; }

    public string Loc_Name { get; set; }

    public string Loc_Lat { get; set; }

    public string Loc_Long { get; set; }

    public string ReadMoreUrl { get; set; }

    public string Loc_Data_Url { get; set; }

}

}
